version: "3.4"

services:
  api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - sqldata

  sqldata:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD="romDb12345"
      - ACCEPT_EULA="Y"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data   
    ports:
      - "1450:1433"  